version: '3'
services:
  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  server:
    image: node:10.16.3
    volumes:
      - "./pangolin-server:/var/www"
    ports: 
      - "8080:8080"
    depends_on:
      - "mongo"
    links:
      - mongo
    environment:
      - URL_MONGO=mongodb://root:root@mongo
    command: bash -c "cd /var/www && npm install && npm start"
  frontend:
    container_name: frontend
    build: ./pangolin-front
    volumes:
      - './pangolin-front:/app'
    ports:
      - '4200:4200'
    command: bash -c "npm install && npm start"
    links:
      - server